apiVersion: opendatahub.io/v1beta1
kind: DataScienceCluster
metadata:
  name: opendatahub
  namespace: opendatahub-applications
spec:
  components:
    dashboard:
      enabled: true
    notebookController:
      enabled: true
      notebookNamespace: opendhatahub-notebooks
      workbenchImages:
        managed: true
    dataSciencePipelinesController:
      enabled: true
    modelMeshController:
      enabled: true
    prometheus:
      enabled: true
    grafana:
      enabled: true
  sso:
    openShiftOAuth: true
