apiVersion: opendatahub.io/v1beta1
kind: DataScienceCluster
metadata:
  name: opendatahub
  namespace: opendatahub-applications
spec:
  components:
    dashboard:
      enabled: true
      rbac:
        admins: cluster-admins
        users: authenticated-users
      replicas: 2
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 2Gi
    notebookController:
      enabled: true
      notebookNamespace: opendhatahub-notebooks # unsure of how I feel about the idea of a namespace scoped object installing stuff in other namespaces.  Chris mentioned this namespace may be going away in the future though.
      workbenchImages:
        managed: true
      resources:
        limits:
          cpu: 500m
          memory: 4Gi
        requests:
          cpu: 500m
          memory: 256Mi
    dataSciencePipelinesController:
      enabled: true
      replicas: 1
      resources:
        limits:
          cpu: 1
          memory: 4Gi
        requests:
          cpu: 10m
          memory: 64Mi
    modelMeshController:
      enabled: true
      replicas: 3
      resources:
        requests:
          cpu: 50m
          memory: 96Mi
        limits:
          cpu: "1"
          memory: 2Gi
    prometheus:
      enabled: true
    grafana:
      enabled: true
  sso:
    openShiftOAuth: true
status:
  conditions:
    - lastTransitionTime: '2021-08-23T16:03:23Z'
      message: All components reporting as healthy
      reason: HealthChecksPassing
      status: 'True'
      type: Available
    - lastTransitionTime: '2021-08-23T16:03:23Z'
      message: All components successfully installed
      reason: Processing
      status: 'False'
      type: ComponentsInstalling
